name: Test Mobile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your code

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # The recommended action for Flutter environment setup
        with:
          channel: 'stable'





      # Install Flutter dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Run Flutter Analyzer
      - name: Analyze Dart Code
        run: flutter analyze

      # Run Unit/Widget Tests
      - name: Run Flutter Tests
        run: flutter test test/counter_test.dart

      # Run Integration Test
      - name: Run Integration Test
        run: flutter test test/integration_test.dart
